server:
  port: 8080

logging:
  level:
    root: warn
    com:
      mak:
        starter: debug
# spring:
#   jpa:
#     open-in-view: false
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#   datasource:
#     url: jdbc:postgresql://localhost:5432/accounting
#     username:
#     password:
#     driver-class-name: org.postgresql.Driver
